workflows:
  ios-release:
    name: Rida iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: 22.11.0

    scripts:
      - name: Test
        script: echo "hello"
